// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agzvbqbywqwrknvuqmxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnenZicWJ5d3F3cmtudnVxbXhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODI3ODAsImV4cCI6MjA2Mzc1ODc4MH0.B8xYfl7riX7moKrp5vxfKB_dYvmx2G7W6Jo6b_6wB-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);